name: Lint Markdown

on:
  push:
    paths:
      - '**.md' # Trigger only when markdown files were changed
  pull_request:
    paths:
      - '**.md' # Trigger only when markdown files were changed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: |
            README.md
